Update testrelease.yaml
Signed-off-by: Mohan E <mohanraj1715@gmail.com>

diff --git a/.github/workflows/testrelease.yaml b/.github/workflows/testrelease.yaml
--- a/.github/workflows/testrelease.yaml
+++ b/.github/workflows/testrelease.yaml
@@ -59,24 +59,31 @@ jobs:
 
               # Construct data payload for tag
               data='{
-                "tag": "'"$TAG"'",
-                "message": "'"$MESSAGE"'",
-                "object": "'"$OBJECT_SHA"'",
-                "type": "'"commit"'"
+                  "tag": "'"$TAG"'",
+                  "message": "'"$MESSAGE"'",
+                  "object": "'"$OBJECT_SHA"'",
+                  "type": "commit"
               }'
 
               # Debugging output
               echo "DEBUG: Data payload for tag:"
               echo "data: $data"
 
-              # Run curl command for tag
-              curl -L \
-                -X POST \
-                -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
-                -H "X-GitHub-Api-Version: 2022-11-28" \
-                https://api.github.com/repos/shubham17998/$REPO/git/tags \
-                -d "$data"
+              # Run curl command for tag and handle errors
+              if response=$(curl -L -sS \
+                  -X POST \
+                  -H "Accept: application/vnd.github+json" \
+                  -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
+                  -H "X-GitHub-Api-Version: 2022-11-28" \
+                  https://api.github.com/repos/shubham17998/$REPO/git/tags \
+                  -d "$data"); then
+                  echo "Tag created successfully."
+                  echo "GitHub API Response: $response"
+              else
+                  echo "Error creating tag."
+                  echo "GitHub API Response: $response"
+                  exit 1
+              fi
             else
 
               # Construct data payload for release
